### PR TITLE
Fix dates in Workflow tab

### LINKED ISSUE #628: Workflow History date and run-time not displaying
Previously, the workflow history of transfers in version 0.41 was not displaying properly. This issue was resolved, but since the resolution was implemented the date and run-time of the activities listed in the workflow history pages are not displaying properly: 
image

### PR DESCRIPTION
**Pull request by DanielCosme**
This MR fix the formatting for dates in the workflow Tab. At some point the Temporal payload for the event history changed and now we need to account for that.

This is how is looks right now: 
image

This is after the fix: 

image

Fixes #628

### CODE REVIEW

File: ui/src/filters/index.ts [hunk 1]
```diff
@@ -2,7 +2,17 @@ import Vue from 'vue';
...
+
+Vue.filter('formatDateTimeString', (value: string | EventTime) => {
+  if (typeof(value) === 'object') {
+     value = value as EventTime
+     const date = fromEventTimeToDate(value);
+    return date.toLocaleString();
+  }
   const date = new Date(value);
   return date.toLocaleString();
 });
```
Comment (sevein) [inline ui/src/filters/index.ts:18]: Not sure if tsc will like this alternative:

```ts
Vue.filter('formatDateTimeString', (value: string | EventTime) => {
  const date = typeof value === 'string'
    ? new Date(value)
    : fromEventTimeToDate(value);
    
  return date.toLocaleString();
});
```

File: ui/src/views/CollectionShowWorkflow.vue [hunk 2]
```diff
@@ -236,9 +237,9 @@ export default class CollectionShowWorkflow extends Vue {
     return desc
   }
 
-  private duration(startedAt: string, completedAt: string): string {
-    const started = new Date(startedAt);
-    const completed = new Date(completedAt);
+  private duration(startedAt: EventTime, completedAt: EventTime): string {
+    const started = new Date(fromEventTimeToDate(startedAt));
+    const completed = new Date(fromEventTimeToDate(completedAt));
```
Comment (sevein) [inline ui/src/views/CollectionShowWorkflow.vue:242]: `fromEventTimeToDate` returns a `Date`.

File: ui/src/filters/index.ts [hunk 3]
```diff
@@ -27,9 +37,15 @@ Vue.filter('formatDuration', (from: Date, to: Date) => {
...
+  const t = fromEventTimeToDate(to)
   const diff = moment(t).diff(f);
   return humanizeDuration(moment.duration(diff).asMilliseconds());
 });
+
+export function fromEventTimeToDate(ev :EventTime): Date {
+  let secondsToMilis = ev.seconds * 1000;
+  let nanosecondsToMilis = ev.nanos / 1_000_000;
+  return new Date(secondsToMilis + nanosecondsToMilis);
+}
```
Comment (sevein) [inline ui/src/filters/index.ts:51]: There's [packages/common/src/time.ts](https://github.com/temporalio/sdk-typescript/blob/HEAD/packages/common/src/time.ts) in the TS SDK if you want a quick, tested conversion helper.

**Review by sevein — APPROVED** [review]
:+1:

File: ui/src/views/CollectionShowWorkflow.vue (hunk 2 above)
Comment (DanielCosme) [reply ui/src/views/CollectionShowWorkflow.vue]: Thank you for catching that one.

File: ui/src/filters/index.ts (hunk 3 above)
Comment (sevein) [reply ui/src/filters/index.ts:47]: Yeah it's overkill

**Review by sevein — APPROVED** [review]
